In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Maternal Health Risk Data Set.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[ 25. 130.  80.  15.  98.  86.]
 [ 35. 140.  90.  13.  98.  70.]
 [ 29.  90.  70.   8. 100.  80.]
 ...
 [ 35.  85.  60.  19.  98.  86.]
 [ 43. 120.  90.  18.  98.  70.]
 [ 32. 120.  65.   6. 101.  76.]]


In [ ]:
print(y)

['high risk' 'high risk' 'high risk' ... 'high risk' 'high risk'
 'mid risk']


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 0 0 ... 0 0 2]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
print(X_train)

[[ 22.  120.   80.    6.9 103.   76. ]
 [ 17.   90.   65.    7.7 103.   67. ]
 [ 23.  140.   90.    6.8  98.   70. ]
 ...
 [ 24.  120.   80.    7.5  98.   66. ]
 [ 35.  100.   70.    7.5  98.   66. ]
 [ 32.  140.  100.    6.9  98.   78. ]]


In [ ]:
print(y_train)

[1 0 0 1 1 0 1 1 0 2 1 0 2 1 0 1 1 0 0 2 1 1 1 1 1 2 0 1 1 1 2 1 2 1 1 2 0
 1 1 2 0 0 0 2 0 0 1 2 1 0 2 0 2 2 1 0 1 1 2 1 1 1 0 0 1 0 0 2 1 1 2 0 0 1
 2 1 0 0 2 0 1 2 2 2 1 1 0 0 2 1 0 1 0 1 0 1 0 1 0 1 0 2 1 0 0 2 2 1 0 2 2
 1 0 1 2 1 0 2 0 1 1 0 1 1 1 0 0 2 2 2 2 2 1 2 1 2 2 1 1 1 2 1 2 1 1 2 0 1
 2 1 2 0 0 0 0 1 1 2 2 2 0 2 2 2 0 2 0 1 1 0 1 0 1 1 0 1 0 0 1 2 1 1 2 2 0
 2 2 2 1 1 1 2 2 2 0 2 0 2 1 0 1 2 2 2 1 0 1 2 1 1 1 1 2 1 1 2 0 1 2 2 0 0
 2 2 1 0 1 2 2 1 0 1 2 0 0 2 1 0 2 2 2 2 1 1 1 1 1 0 0 1 2 1 2 1 0 1 1 2 2
 1 1 2 1 2 0 1 0 2 0 2 2 2 0 1 2 2 1 0 1 1 2 0 0 2 2 1 0 0 2 2 1 0 1 0 2 0
 0 2 2 1 2 0 1 1 0 0 0 1 0 1 2 2 2 2 0 0 1 0 2 0 2 2 2 2 0 0 2 0 1 0 1 2 2
 0 0 0 2 2 1 1 1 0 1 0 1 2 1 2 0 1 1 1 0 0 0 0 0 2 1 1 1 0 1 2 1 2 1 2 1 2
 0 0 2 0 1 2 1 1 0 2 1 0 2 1 1 1 2 1 1 1 1 2 1 2 1 0 1 2 0 1 0 0 0 2 2 1 0
 0 1 0 0 0 2 1 0 1 1 1 1 0 0 1 1 2 1 0 2 1 1 2 2 2 1 2 1 2 0 2 0 0 2 2 1 2
 1 1 2 2 1 1 1 2 1 1 1 1 0 0 2 0 0 1 1 1 2 1 2 2 2 0 2 0 1 1 1 1 2 0 1 1 2
 1 0 1 0 0 2 0 2 2 1 2 1 

In [ ]:
print(X_test)

[[ 23.  120.   90.    7.5  98.   70. ]
 [ 23.  130.   70.    6.9  98.   70. ]
 [ 35.  100.   70.    7.5  98.   66. ]
 ...
 [ 19.  120.   80.    7.   98.   70. ]
 [ 22.  100.   65.    7.5  98.   70. ]
 [ 32.  120.   90.    7.5  98.   70. ]]


In [ ]:
print(y_test)

[1 2 1 0 2 0 0 0 1 1 1 2 1 2 1 1 2 0 0 1 2 1 2 0 2 2 2 2 2 2 0 2 2 0 2 2 0
 2 0 0 1 1 1 2 2 1 0 1 1 1 2 1 0 0 2 2 0 0 1 0 1 0 0 1 0 2 1 2 0 1 2 0 2 1
 2 1 2 1 2 1 2 0 1 1 1 2 1 0 1 0 1 0 2 1 0 1 2 2 2 0 0 2 1 1 1 2 1 2 2 2 1
 0 2 1 2 0 1 0 2 0 2 2 2 2 1 1 2 1 1 1 1 2 2 1 1 2 2 2 1 1 1 1 2 0 2 1 2 2
 2 2 2 1 1 0 1 1 1 1 1 2 1 2 2 0 1 1 2 1 1 0 2 2 2 2 0 0 2 1 0 0 1 2 0 0 2
 0 1 0 0 2 2 0 1 2 0 0 2 1 1 2 1 1 0 0 2 0 2 0 2 1 0 0 0 2 1 0 1 1 1 2 1 0
 0 1 2 1 1 1 1 1 0 1 1 0 1 2 1 2 2 2 0 1 0 1 2 1 2 0 0 2 0 2 2 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.60158195  0.36677854  0.25283285 -0.55181494  3.07668957  0.19721219]
 [-0.97100848 -1.27615872 -0.83853197 -0.30466871  3.07668957 -0.89239313]
 [-0.52769664  1.46207005  0.98040939 -0.58270822 -0.49582781 -0.52919136]
 ...
 [-0.45381133  0.36677854  0.25283285 -0.36645527 -0.49582781 -1.01346039]
 [ 0.35892704 -0.72851297 -0.47474369 -0.36645527 -0.49582781 -1.01346039]
 [ 0.13727112  1.46207005  1.70798594 -0.55181494 -0.49582781  0.43934671]]


In [ ]:
print(X_test)

[[-0.52769664  0.36677854  0.98040939 -0.36645527 -0.49582781 -0.52919136]
 [-0.52769664  0.91442429 -0.47474369 -0.55181494 -0.49582781 -0.52919136]
 [ 0.35892704 -0.72851297 -0.47474369 -0.36645527 -0.49582781 -1.01346039]
 ...
 [-0.82323787  0.36677854  0.25283285 -0.52092166 -0.49582781 -0.52919136]
 [-0.60158195 -0.72851297 -0.83853197 -0.36645527 -0.49582781 -0.52919136]
 [ 0.13727112  0.36677854  0.98040939 -0.36645527 -0.49582781 -0.52919136]]


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [2 2]
 [1 1]
 [1 2]
 [2 0]
 [1 2]
 [1 2]
 [2 2]
 [2 2]
 [1 2]
 [2 2]
 [1 0]
 [0 2]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [0 0]
 [2 2]
 [2 0]
 [0 0]
 [1 1]
 [2 1]
 [1 1]
 [2 2]
 [2 2]
 [2 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [0 0]
 [0 0]
 [2 2]
 [2 2]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 2]
 [1 1]
 [2 2]
 [0 0]
 [1 1]
 [2 2]
 [2 0]
 [2 2]
 [2 1]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [2 0]
 [0 1]
 [2 1]
 [1 1]
 [2 2]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [2 0]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [0 0]
 [0 0]
 [0 2]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 2]
 [1 2]
 [0 2]
 [1 1]
 [0 0]
 [2 2]
 [0 1]
 [2 2]
 [0 0]
 [2 1]
 [0 0]
 [2 2]
 [0 0]
 [2 2]
 [2 2]
 [2 2]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [2 1]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [2 1]
 [2 2]

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[54  4  9]
 [ 4 76 15]
 [ 5 17 70]]


0.7874015748031497

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.81      0.83        67
           1       0.78      0.80      0.79        95
           2       0.74      0.76      0.75        92

    accuracy                           0.79       254
   macro avg       0.80      0.79      0.79       254
weighted avg       0.79      0.79      0.79       254

